# Generated by Django 4.1.3 on 2022-11-23 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('geb', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
                ('memberNr', models.CharField(default='not a member', max_length=200)),
                ('food', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.slot')),
            ],
        ),
        migrations.CreateModel(
            name='Participant2Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref', models.CharField(default='', max_length=200)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.participant')),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.seminar')),
            ],
        ),
    ]
